### ISSUE TITLE
[Suggestion][SFX] Have user join/leave sound override guild

### ISSUE THREAD

**Issue by cag1585** [kaogurai/cogs#13]
I think it would work better if you can set a guild wide clip and users can set their own. 
And if they have one set it overrides the guild so we can still have both options.
I'm using mock but it would be nice if admins could set one for the user as well!

Thanks for the cog!

**Comment by Ryan5453** [comment]
I think it makes sense to add a toggle for if guild or user should have priority.

However, I won't be adding a toggle for admins being able to change the user's sound since it is a user setting, not a member setting so admins should not have the right to change settings across servers. Possibly I could add a command to disable a user's sound, but only in that server. Or maybe instead a command for the owner to change it. Or both.

**Comment by Ryan5453** [comment]
I've added a toggle for whether user or guild sounds should have priority in v7.1.0. As mentioned above I won't be added a command for admins to change user's sounds. This will be published soon
