### ISSUE TITLE
[Suggestion][SFX] Suggestions for TTS

### ISSUE THREAD

**Issue by sleepymanakete** [kaogurai/cogs#15]
Hi!
 I have some suggestions/requests for the SFX cog:
1. Have the bot say the name of the person that typed in the tts channel like the Hawking the bot does.
2. An option to turn off the "you are not in a vc" message.
3. When someone posts a link/image, the bot says "[Name] posted a link/image"

Thanks for the cog, its very helpful!

**Comment by Ryan5453** [comment]
1. This definitely will not be default behavior, however it makes sense to add it as an option for the server admins/mods.
2. I don't think this is the best idea to be included because for TTS you really need to be in the VC to be able to use it well since you need to know the context of the conversation, and I think SFX will just be abused a lot.
3. Good idea. I think what I will do is piggyback of the settings from your first suggestion on whether or not to say the user's name, though.

**Comment by Ryan5453** [comment]
Above will be implemented in v7.1.0.
